apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret-prod
  dnsNames:
  - staging.maiaphr.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - staging.maiaphr.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
