apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: apostrophe-maia2
  namespace: maia2
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
          #set_cookie_flag * secure SameSite;
          more_set_headers "X-Frame-Options: DENY";
          more_set_headers "x-xss-protection: 1; mode=block";
          more_set_headers 'X-Content-Type-Options: nosniff';
          more_set_headers 'Referrer-Policy: no-referrer';
          more_set_headers 'X-Permitted-Cross-Domain-Policies: none';
          more_set_headers 'X-Download-Options: noopen';
          more_set_headers 'X-Robots-Tag: none';
          more_clear_headers 'X-Powered-By';
          more_clear_headers 'server';
          add_header Cache-Control "no-cache, no-store, must-revalidate";
          sub_filter 'nginx'  '';
spec:
  tls:
  - hosts:
    - staging.maiaphr.com
    secretName: tls-secret-prod
  rules:
  - host: staging.maiaphr.com
    http:
      paths:
      - backend:
          serviceName: apostrophe-maia2
          servicePort: 80
        path: /
