apiVersion: v1
kind: Namespace
metadata:
  name: $MAIA3_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-controller
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    matchLabels:
      app: phr-${MAIA3_NAMESPACE}-service-controller
  template:
    metadata:
      labels:
        app: phr-${MAIA3_NAMESPACE}-service-controller
    spec:
      containers:
      - name: phr-${MAIA3_NAMESPACE}-service-controller
        image: ${PHR_REGISTRY}/phr-${MAIA3_NAMESPACE}-service-controller:v${BUILD_NUMBER}
        env:
          - name: PORT
            value: '3000'
          - name: APP_NAME
            value: service-controller
          - name: HOST
            value: 0.0.0.0
          - name: NODE_ENV
            value: development
          - name: JWTSECRET
            value: ${PHR_MAIA3_JWT_SECRET_KEY}
          - name: REDIS_PORT
            value: ${PHR_MAIA3_REDIS_PORT}
          - name: REDIS_HOST
            value: ${PHR_MAIA3_REDIS_HOST}
          - name: REDIS_PASSWORD
            value: ${PHR_MAIA3_REDIS_PASSWORD}
          - name: DATABASE_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-database:3001
          - name: AUTH_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-authentication:3002
          - name: ALCOHOL_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-alcohol:3004
          - name: SLEEP_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-sleep:3005
          - name: MOOD_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-mood:3006
          - name: SMOKE_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-smoke:3007
          - name: BMI_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-bmi:3008
          - name: BLOOD_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-blood:3009
          - name: TEMPERATURE_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-temperature:3010
          - name: PROBLEM_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-problem:3011
          - name: PAIN_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-pain:3012
          - name: COPING_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-coping:3013
          - name: DIARY_URL
            value:  http://phr-${MAIA3_NAMESPACE}-service-diary:3014
          - name: EMAIL_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-email:4000
          - name: USER_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-user:3003
          - name: CACHE_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-cache:4001
          - name: HEALTH_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-health:3015
          - name: CIRCLE_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-circle:3016
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: '0'
          - name: CRON_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-cron:3017
          - name: APP_SETTINGS_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-appsettings:3018
          - name: UPLOAD
            value: http://phr-${MAIA3_NAMESPACE}-service-upload:3019
          - name: GOAL_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-goal:3020
          - name: RESOURCE_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-resource:3021
          - name: NOTIFICATION_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-notification:3022
          - name: FITBIT_URL
            value: http://phr-${MAIA3_NAMESPACE}-service-fitbit:3023
          - name: APPOINTMENT_URL
            value : http://phr-${MAIA3_NAMESPACE}-service-appointment:3024
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-controller
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    app: phr-${MAIA3_NAMESPACE}-service-controller
  ports:
  - port: 3000
  type : NodePort
