apiVersion: v1
kind: Namespace
metadata:
  name: $MAIA3_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-database
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    matchLabels:
      app: phr-${MAIA3_NAMESPACE}-service-database
  template:
    metadata:
      labels:
        app: phr-${MAIA3_NAMESPACE}-service-database
    spec:
      containers:
      - name: phr-${MAIA3_NAMESPACE}-service-database
        image: ${PHR_REGISTRY}/phr-${MAIA3_NAMESPACE}-service-database:v${BUILD_NUMBER}
        env:
        - name: NODE_ENV
          value: development
        - name: APP_NAME
          value: service-database
        - name: PORT
          value: '3001'
        - name: PG_DB
          value: ${MAIA3_POSTGRES_DB}
        - name: PG_USER
          value: ${MAIA3_POSTGRES_USER}
        - name: PG_PASSWORD
          value: ${MAIA3_POSTGRES_PASSWORD}
        - name: PG_HOST
          value: ${MAIA3_POSTGRES_HOST}
        - name: PG_PORT
          value: ${MAIA3_POSTGRES_PORT}
        - name: SSL
          value: ${MAIA3_DB_SSL}
        - name: AUTH_URL
          value: http://phr-${MAIA3_NAMESPACE}-service-authentication:3002
        - name: EMAIL_URL
          value: http://phr-${MAIA3_NAMESPACE}-service-email:4000
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          value: '0'
        - name: ATTEMPT_TIME_LIMIT
          value: '10'
        - name: HOST
          value: '0.0.0.0'
        - name: JWTSECRET
          value: ${PHR_MAIA3_JWT_SECRET_KEY}
        - name: ACCESS_TOKEN_EXPIRY
          value: ${MAIA3_ACCESS_TOKEN_EXPIRY}
        - name: REFRESH_TOKEN_EXPIRY
          value: ${MAIA3_REFRESH_TOKEN_EXPIRY}
        - name: RESET_PASSWORD_TOKEN_EXPIRY
          value: ${MAIA3_RESET_PASSWORD_TOKEN_EXPIRY}
        - name: REDIS_URL
          value: http://phr-${MAIA3_NAMESPACE}-service-cache:4001
        - name: HAS_AUDIT_TRAIL
          value: 'true'
        - name: TPJWTSECRET
          value: ${MAIA3_TPJWTSECRET}
        - name: TPCLIENTID
          value: ${MAIA3_TPCLIENTID}
        - name: TPID
          value: ${MAIA3_TPID}
        - name: FITBIT_CLIENT_ID
          value: ${MAIA3_FITBIT_CLIENT_ID}
        - name: SCOPE
          value: ${MAIA3_SCOPE}
        - name: RESPONSE_TYPE
          value: ${MAIA3_RESPONSE_TYPE}
        - name: CLIENT_SECRET
          value: ${MAIA3_CLIENT_SECRET}
        - name: REDIRECT_URL
          value: ${MAIA3_REDIRECT_URL}
        - name: AUTHORIZATION_URL
          value: ${MAIA3_AUTHORIZATION_URL}
        - name: REFRESH_TOKEN_URL
          value: ${MAIA3_REFRESH_TOKEN_URL}
        - name: FITBIT_BASE_URL
          value: ${MAIA3_FITBIT_BASE_URL}
        - name: RESOURCE_URL
          value: ${MAIA3_RESOURCE_URL}
        - name: CLIENT_ID
          value: ${MAIA3_CLIENT_ID}
        - name: CLIENT_SECRET
          value: ${MAIA3_CLIENT_SECRET}
        - name: CIRCLE_URL
          value: http://phr-${MAIA3_NAMESPACE}-service-circle:3016
        - name: AMQP_URL
          value: amqp://guest:guest@51.11.29.202:5672
        - name: NOTIFICATION_URL
          value: http://phr-${MAIA3_NAMESPACE}-service-notification:3022

        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-database
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    app: phr-${MAIA3_NAMESPACE}-service-database
  ports:
  - port: 3001
