apiVersion: v1
kind: Namespace
metadata:
  name: $MAIA3_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-authentication
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    matchLabels:
      app: phr-${MAIA3_NAMESPACE}-service-authentication
  template:
    metadata:
      labels:
        app: phr-${MAIA3_NAMESPACE}-service-authentication
    spec:
      containers:
      - name: phr-${MAIA3_NAMESPACE}-service-authentication
        image: ${PHR_REGISTRY}/phr-${MAIA3_NAMESPACE}-service-authentication:v${BUILD_NUMBER}
        env:
        - name: PORT
          value: '3002'
        - name: HOST
          value: 0.0.0.0
        - name: DATABASE_URL
          value: http://phr-${MAIA3_NAMESPACE}-service-database:3001
        - name: NODE_ENV
          value: development
        - name: NHS_LOGIN_PRIVATE_KEY_PATH
          value: /etc/ssl/certs/private_key.pem
        - name: NHS_LOGIN_CLIENT_REDIRECT_URL
          value: ${MAIA3_NHS_LOGIN_CLIENT_REDIRECT_URL}
        - name: NHS_LOGIN_CLIENT_ID
          value: ${MAIA3_NHS_LOGIN_CLIENT_ID}
        - name: NHS_LOGIN_AUTHORIZATION_URL
          value: ${MAIA3_NHS_LOGIN_AUTHORIZATION_URL}
        - name: NHS_LOGIN_AUDIENCE
          value: ${MAIA3_NHS_LOGIN_AUDIENCE}
        - name: NHS_LOGIN_TOKEN_HOST
          value: ${MAIA3_NHS_LOGIN_TOKEN_HOST}
        - name: FHIR_SERVER
          value: ${PHR_MAIA3_FHIR_SERVER}
        - name: FHIR_TAG_URL
          value: ${PHR_MAIA3_FHIR_TAG_URL}
        - name: FHIR_TAG_CODE
          value: ${PHR_MAIA3_FHIR_TAG_CODE}
        volumeMounts:
        - name: nhs-pemstore
          mountPath: /etc/ssl/certs/private_key.pem
          subPath: private_key.pem
          readOnly: false
        ports:
        - containerPort: 80
        imagePullPolicy: Always
      volumes:
      - name: nhs-pemstore
        configMap:
          name: nhs-pemstore
---
apiVersion: v1
kind: Service
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-authentication
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    app: phr-${MAIA3_NAMESPACE}-service-authentication
  ports:
  - port: 3002
