apiVersion: v1
kind: Namespace
metadata:
  name: $MAIA3_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-sleep
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    matchLabels:
      app: phr-${MAIA3_NAMESPACE}-service-sleep
  template:
    metadata:
      labels:
        app: phr-${MAIA3_NAMESPACE}-service-sleep
    spec:
      containers:
      - name: phr-${MAIA3_NAMESPACE}-service-sleep
        image: ${PHR_REGISTRY}/phr-${MAIA3_NAMESPACE}-service-sleep:v${BUILD_NUMBER}
        env:
        - name: PORT
          value: '3005'
        - name: HOST
          value: 0.0.0.0
        - name: DATABASE_URL
          value: http://phr-${MAIA3_NAMESPACE}-service-database:3001
        - name: NODE_ENV
          value: development
        - name: FHIR_SERVER
          value: ${PHR_MAIA3_FHIR_SERVER}
        - name: FHIR_TAG_URL
          value: ${PHR_MAIA3_FHIR_TAG_URL}
        - name: FHIR_TAG_CODE
          value: ${PHR_MAIA3_FHIR_TAG_CODE}
        ports:
        - containerPort: 3005
---
apiVersion: v1
kind: Service
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-sleep
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    app: phr-${MAIA3_NAMESPACE}-service-sleep
  ports:
  - port: 3005
