apiVersion: v1
kind: Namespace
metadata:
  name: $MAIA3_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-appsettings
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    matchLabels:
      app: phr-${MAIA3_NAMESPACE}-service-appsettings
  template:
    metadata:
      labels:
        app: phr-${MAIA3_NAMESPACE}-service-appsettings
    spec:
      containers:
      - name: phr-${MAIA3_NAMESPACE}-service-appsettings
        image: ${PHR_REGISTRY}/phr-${MAIA3_NAMESPACE}-service-appsettings:v${BUILD_NUMBER}
        env:
        - name: PORT
          value: '3018'
        - name: HOST
          value: 0.0.0.0
        - name: DATABASE_URL
          value: http://phr-${MAIA3_NAMESPACE}-service-database:3001
        - name: NODE_ENV
          value: development
        ports:
        - containerPort: 3018
---
apiVersion: v1
kind: Service
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-appsettings
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    app: phr-${MAIA3_NAMESPACE}-service-appsettings
  ports:
  - port: 3018
