apiVersion: v1
kind: Namespace
metadata:
  name: $MAIA3_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-resource
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    matchLabels:
      app: phr-${MAIA3_NAMESPACE}-service-resource
  template:
    metadata:
      labels:
        app: phr-${MAIA3_NAMESPACE}-service-resource
    spec:
      containers:
      - name: phr-${MAIA3_NAMESPACE}-service-resource
        image: ${PHR_REGISTRY}/phr-${MAIA3_NAMESPACE}-service-resource:v${BUILD_NUMBER}
        env:
        - name: PORT
          value: '3021'
        - name: HOST
          value: 0.0.0.0
        - name: DATABASE_URL
          value: http://phr-${MAIA3_NAMESPACE}-service-database:3001
        - name: NODE_ENV
          value: development
        - name: FHIR_SERVER
          value: ${PHR_MAIA3_FHIR_SERVER}
        - name: FHIR_TAG_URL
          value: ${PHR_MAIA3_FHIR_TAG_URL}
        - name: FHIR_TAG_CODE
          value: 'maia-development'
        - name: RESOURCE_URL
          value: ${PHR_MAIA3_RESOURCE_URL}
        - name: CLIENT_ID
          value: ${PHR_MAIA3_CLIENT_ID}
        - name: CLIENT_SECRET
          value: ${PHR_MAIA3_CLIENT_SECRET}
        ports:
        - containerPort: 3021
---
apiVersion: v1
kind: Service
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-resource
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    app: phr-${MAIA3_NAMESPACE}-service-resource
  ports:
  - port: 3021

