apiVersion: v1
kind: Namespace
metadata:
  name: $MAIA3_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-appointment
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    matchLabels:
      app: phr-${MAIA3_NAMESPACE}-service-appointment
  template:
    metadata:
      labels:
        app: phr-${MAIA3_NAMESPACE}-service-appointment
    spec:
      containers:
      - name: phr-${MAIA3_NAMESPACE}-service-appointment
        image: ${PHR_REGISTRY}/phr-${MAIA3_NAMESPACE}-service-appointment:v${BUILD_NUMBER}
        env:
        - name: PORT
          value: '3024'
        - name: HOST
          value: 0.0.0.0
        - name: DATABASE_URL
          value: http://phr-${MAIA3_NAMESPACE}-service-database:3001
        - name: NODE_ENV
          value: development
        - name: FHIR_SERVER
          value: ${PHR_MAIA3_FHIR_SERVER}
        - name: FHIR_TAG_URL
          value: ${PHR_MAIA3_FHIR_TAG_URL}
        - name: FHIR_TAG_CODE
          value: 'maia-development'
        ports:
        - containerPort: 3024
---
apiVersion: v1
kind: Service
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-appointment
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    app: phr-${MAIA3_NAMESPACE}-service-appointment
  ports:
  - port: 3024

