apiVersion: v1
kind: Namespace
metadata:
  name: $MAIA3_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-email
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    matchLabels:
      app: phr-${MAIA3_NAMESPACE}-service-email
  template:
    metadata:
      labels:
        app: phr-${MAIA3_NAMESPACE}-service-email
    spec:
      containers:
      - name: phr-${MAIA3_NAMESPACE}-service-email
        image: ${PHR_REGISTRY}/phr-${MAIA3_NAMESPACE}-service-email:v${BUILD_NUMBER}
        env:
        - name: PORT
          value: '4000'
        - name: HOST
          value: 0.0.0.0
        - name: SENDGRID_API_KEY
          value: ${MAIA3_SENDGRID_API_KEY}
        - name: FROM_MAIL_ID
          value: ${MAIA3_FROM_MAIL_ID}
        - name: DATABASE_URL
          value: http://phr-${MAIA3_NAMESPACE}-service-database:3001
        - name: FRONT_END_DOMAIN_URL
          value: ${MAIA3_FRONT_END_DOMAIN_URL}
        ports:
        - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-email
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    app: phr-${MAIA3_NAMESPACE}-service-email
  ports:
  - port: 4000
