apiVersion: v1
kind: Namespace
metadata:
  name: $MAIA3_NAMESPACE
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-cache
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    matchLabels:
      app: phr-${MAIA3_NAMESPACE}-service-cache
  template:
    metadata:
      labels:
        app: phr-${MAIA3_NAMESPACE}-service-cache
    spec:
      containers:
      - name: phr-${MAIA3_NAMESPACE}-service-cache
        image: ${PHR_REGISTRY}/phr-${MAIA3_NAMESPACE}-service-cache:v${BUILD_NUMBER}
        env:
        - name: PORT
          value: '4001'
        - name: HOST
          value: 0.0.0.0
        - name: DATABASE_URL
          value: http://phr-${MAIA3_NAMESPACE}-service-database:3001
        - name: NODE_ENV
          value: development
        - name: REDIS_PORT
          value: ${PHR_MAIA3_REDIS_PORT}
        - name: REDIS_HOST
          value: ${PHR_MAIA3_REDIS_HOST}
        - name: REDIS_PASSWORD
          value: ${PHR_MAIA3_REDIS_PASSWORD}  
        ports:
        - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: phr-${MAIA3_NAMESPACE}-service-cache
  namespace: $MAIA3_NAMESPACE
spec:
  selector:
    app: phr-${MAIA3_NAMESPACE}-service-cache
  ports:
  - port: 4001
